# Generated by Django 4.2.3 on 2023-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_stockownedmodel_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockownedmodel",
            name="buy_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
