# Generated by Django 4.2.3 on 2023-08-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_stockownedmodel_buy_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockownedmodel",
            name="buy_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockownedmodel",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
